In [104]:
# Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
# sklearn.datasets.
import seaborn as sns 
df = sns.load_dataset('iris')

In [105]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [103]:
df.shape

(506, 14)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [65]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [66]:
df_drop = df[df.duplicated()]
df_drop

sepal_length  sepal_width  petal_length  petal_width    species
142           5.8          2.7           5.1          1.9  virginica

In [67]:
df_drop = df.drop(df.index[142])

In [68]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [69]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
df['species'] = le.fit_transform(df['species'])
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [70]:
# Independent and dependent 
X = df.drop(labels=['species'],axis=1)
y = df['species']

In [71]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [72]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [74]:
from sklearn.neighbors import KNeighborsClassifier
KNC = KNeighborsClassifier(n_neighbors=6,algorithm='auto')
KNC.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [75]:
y_pred = KNC.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [76]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Accuracy_Score :',accuracy_score(y_test,y_pred))
print('Confusion_Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification_Report :\n',classification_report(y_test,y_pred))

Accuracy_Score : 0.98
Confusion_Matrix :
 [[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]

Classification_Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [77]:
# Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
# sklearn.datasets.
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [78]:
df.shape

(506, 14)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [80]:
df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [81]:
df[df.duplicated()]

Empty DataFrame
Columns: [crim, zn, indus, chas, nox, rm, age, dis, rad, tax, ptratio, b, lstat, medv]
Index: []

In [82]:
# Independent and dependent
X = df.drop(labels=['medv'],axis=1)
y = df['medv']

In [83]:
X.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  
0  396.90   4.98  
1  396.90   9.14  
2  392.83   4.03  
3  394.63   2.94  
4  396.90   5.33

In [84]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [85]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=45)

In [86]:
from sklearn.neighbors import KNeighborsRegressor
KNR = KNeighborsRegressor(n_neighbors=10,algorithm='auto')
KNR.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=10)

In [88]:
y_pred = KNR.predict(X_test)

In [90]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
print('R2_Score :',r2_score(y_test,y_pred))
print('MSE :',mean_squared_error(y_test,y_pred))
print('MAE :',mean_absolute_error(y_test,y_pred))

R2_Score : 0.42730363119703896
MSE : 61.895863725490194
MAE : 5.4322549019607855


In [92]:
# Hyperparameter tunning 
parameter = {
    'n_neighbors': [3, 5, 7, 9, 11],  
    'weights': ['uniform', 'distance'], 
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],  
    'p': [1, 2] 
}

In [94]:
from sklearn.model_selection import GridSearchCV
KNNGSCV = GridSearchCV(KNeighborsRegressor(),param_grid=parameter,cv=5,verbose=3,scoring='r2')
KNNGSCV.fit(X_train,y_train)

Fitting 5 folds for each of 80 candidates, totalling 400 fits
[CV 1/5] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.461 total time=   0.0s
[CV 2/5] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.667 total time=   0.0s
[CV 3/5] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.451 total time=   0.0s
[CV 4/5] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.625 total time=   0.0s
[CV 5/5] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.619 total time=   0.0s
[CV 1/5] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.536 total time=   0.0s
[CV 2/5] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.674 total time=   0.0s
[CV 3/5] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.502 total time=   0.0s
[CV 4/5] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.623 total time=   0.0s
[CV 5/5] END algorithm=auto, n_neighbors=3, p=1, wei

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='r2', verbose=3)

In [95]:
KNNGSCV.best_params_

{'algorithm': 'auto', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [99]:
y_pred = KNNGSCV.predict(X_test)
y_pred

array([18.90733513, 28.25228087, 21.43303442, 21.08122549, 27.01951941,
       12.73905238, 20.56255173, 25.88323824, 22.62036362, 17.38510242,
       11.02561007, 13.74776374, 24.37172267, 22.86545392, 20.63101541,
       15.50579875, 21.74740172, 22.53467134,  8.67896927, 33.37872662,
       23.15966864, 24.03301279, 29.42254646, 27.81910901, 20.38715043,
       22.06465456, 23.84378187, 16.11661992, 19.69696011, 20.40947858,
       22.14830382, 10.87885573, 25.71316271, 22.54263673, 37.70938798,
       23.04514577, 28.80937139,  8.12617017, 34.43699902, 39.08487587,
       24.21118115, 21.10912954, 18.7794654 , 35.97202908, 18.34020405,
       10.28169047, 26.74668814, 22.24140966, 18.06925846, 19.95718635,
       46.20916702, 21.97204488, 26.32200362, 34.01971206, 17.41809816,
       29.48276426,  9.69221494, 16.34293085, 20.16489204, 24.35678282,
       13.92538791, 16.68332465, 39.18142707, 41.76781939, 14.09084333,
       21.44668325, 28.87987793, 32.70315216, 30.18356202, 19.15

In [ ]:
print('R2_Score :',r2_score(y_test,y_pred))
print('MSE :',mean_squared_error(y_test,y_pred))
print('MAE :',mean_absolute_error(y_test,y_pred))

R2_Score : 0.5924858649073299
MSE : 44.04330243027114
MAE : 4.615261124670683


In [106]:
# Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
# cross-validation on load_iris dataset in sklearn.datasets.
from sklearn.datasets import load_iris
X,y = load_iris(return_X_y=True)

In [121]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=30)

In [122]:
from sklearn.neighbors import KNeighborsClassifier
KNCla = KNeighborsClassifier()
KNCla.fit(X_train,y_train)

KNeighborsClassifier()

In [123]:
y_pred = KNCla.predict(X_test)
y_pred

array([0, 0, 0, 2, 1, 1, 2, 2, 1, 2, 0, 2, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0,
       0, 0, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 2, 2, 1, 2])

In [124]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Accuracy_Score :',accuracy_score(y_test,y_pred))
print('Confusion_Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification_Report :\n',classification_report(y_test,y_pred))

Accuracy_Score : 0.9210526315789473
Confusion_Matrix :
 [[12  0  0]
 [ 0  9  2]
 [ 0  1 14]]

Classification_Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.90      0.82      0.86        11
           2       0.88      0.93      0.90        15

    accuracy                           0.92        38
   macro avg       0.92      0.92      0.92        38
weighted avg       0.92      0.92      0.92        38



In [125]:
# Hyperparameter Tunning
parameter = {
    'n_neighbors' : [1,2,3,4,5,6,7,8,10],
    'weights' : ['uniform', 'distance'],
    'algorithm' : ['auto','kd_tree','ball_tree','brute'],
    'p' : [1,2]
}

In [126]:
from sklearn.model_selection import RandomizedSearchCV
Rscv = RandomizedSearchCV(KNeighborsClassifier(),param_distributions=parameter,cv=5,scoring='accuracy')
Rscv.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(),
                   param_distributions={'algorithm': ['auto', 'kd_tree',
                                                      'ball_tree', 'brute'],
                                        'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8,
                                                        10],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   scoring='accuracy')

In [127]:
Rscv.best_params_

{'weights': 'distance', 'p': 2, 'n_neighbors': 6, 'algorithm': 'kd_tree'}

In [128]:
y_pred = Rscv.predict(X_test)
y_pred

array([0, 0, 0, 2, 1, 1, 2, 2, 1, 2, 0, 2, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0,
       0, 0, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 2, 2, 1, 2])

In [129]:
print('Accuracy_Score :',accuracy_score(y_test,y_pred))
print('Confusion_Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification_Report :\n',classification_report(y_test,y_pred))

Accuracy_Score : 0.9210526315789473
Confusion_Matrix :
 [[12  0  0]
 [ 0  9  2]
 [ 0  1 14]]

Classification_Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.90      0.82      0.86        11
           2       0.88      0.93      0.90        15

    accuracy                           0.92        38
   macro avg       0.92      0.92      0.92        38
weighted avg       0.92      0.92      0.92        38



In [149]:
# Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
# sklearn.datasets.
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [150]:
X = df.drop(labels=['medv'],axis=1)
y = df['medv'] 

In [152]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=40)

In [153]:
# Feature Scailing
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [154]:
X_train_scaled

array([[-0.46520718, -0.5026534 , -0.16624169, ...,  0.32193319,
         0.44706486, -0.04508458],
       [-0.44545793, -0.5026534 , -0.50505492, ...,  0.51734116,
         0.38484331, -0.08636701],
       [-0.3255001 , -0.5026534 , -0.3935839 , ...,  1.20126905,
        -0.52906945,  0.76068728],
       ...,
       [-0.47034223,  0.03822872, -0.43318545, ..., -1.6321465 ,
         0.44706486,  1.04660633],
       [-0.47575225, -0.5026534 ,  0.44978236, ..., -1.04592259,
         0.41298859, -0.27596039],
       [-0.4419673 , -0.5026534 , -0.50505492, ...,  0.51734116,
         0.44706486, -0.9410662 ]])

In [155]:
X_test_scaled

array([[ 0.43261693, -0.5026534 ,  1.06727314, ...,  0.81045311,
         0.43121292, -0.12612046],
       [-0.48782035,  2.95899216, -1.36455515, ..., -2.90229829,
        -0.01221   , -0.5649374 ],
       [-0.45082331, -0.5026534 , -0.57399095, ..., -0.31314271,
         0.44706486,  2.82939569],
       ...,
       [-0.48907912, -0.5026534 , -0.82626747, ...,  0.81045311,
         0.44706486, -0.65667613],
       [-0.40476493, -0.5026534 , -0.67812835, ..., -0.55740267,
         0.37341266, -1.1581812 ],
       [ 0.97653287, -0.5026534 ,  1.06727314, ...,  0.81045311,
         0.22028509,  0.67812242]])

In [156]:
from sklearn.neighbors import KNeighborsRegressor
KNReg = KNeighborsRegressor(n_neighbors=5)
KNReg.fit(X_train_scaled,y_train)

KNeighborsRegressor()

In [157]:
y_pred = KNReg.predict(X_test_scaled)
y_pred

array([32.22, 30.9 , 17.22, 13.9 , 20.66, 32.08, 24.7 , 16.9 , 20.48,
       12.1 , 24.7 , 16.06, 11.46,  9.02, 22.54, 29.6 , 26.46, 13.28,
       13.2 ,  9.7 , 36.16, 13.08, 38.14, 25.44, 42.22, 25.4 , 23.  ,
       18.08, 18.08, 19.58, 22.46, 21.46, 26.9 , 22.22,  9.6 , 23.72,
       23.72, 10.76, 36.16, 25.64, 22.7 ,  9.12, 18.84, 23.26, 21.7 ,
       10.12, 14.1 , 28.62, 24.32, 33.6 , 16.82, 20.76, 20.24,  9.22,
        9.64, 32.38, 21.7 , 22.4 , 22.4 , 16.4 , 21.58, 11.12, 29.92,
       18.04, 26.32, 18.34, 12.38, 28.06, 30.22, 20.78, 19.06, 24.44,
       15.2 , 29.84, 36.1 , 19.66, 11.6 , 23.68, 21.1 , 22.36, 23.82,
       22.04, 13.62, 11.36, 14.64, 12.7 , 19.62, 14.2 , 21.46, 20.32,
       29.76, 16.4 , 18.98, 10.36, 19.26,  9.02, 17.72, 22.82, 20.44,
       20.46, 21.46, 20.98, 24.34,  9.78, 33.24, 21.7 , 28.58, 31.54,
       21.38, 11.34, 27.04, 37.06, 25.4 , 21.7 , 21.7 , 15.9 , 19.54,
       18.56, 37.72, 21.76, 22.14, 26.38, 27.74, 13.28, 36.16, 15.34,
        9.22, 24.88,

In [158]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
print('R2_Score :',r2_score(y_test,y_pred))
print('MSE :',mean_squared_error(y_test,y_pred))
print('MAE :',mean_absolute_error(y_test,y_pred))

R2_Score : 0.7124542446355274
MSE : 30.673264670658675
MAE : 3.4388023952095805


In [159]:
# Hyperparameter tunning 
parameter = {
    'n_neighbors': [2,4, 6, 8, 10],  
    'weights': ['uniform', 'distance'], 
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],  
    'p': [1, 2] 
}

In [160]:
from sklearn.model_selection import GridSearchCV
GSCV = GridSearchCV(KNeighborsRegressor(),param_grid=param_grid,cv=5)
GSCV.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']})

In [161]:
GSCV.best_params_

{'algorithm': 'auto', 'n_neighbors': 7, 'p': 1, 'weights': 'distance'}

In [162]:
import warnings
warnings.filterwarnings('ignore')
y_pred = GSCV.predict(X_test_scaled)
y_pred 

array([29.89248172, 27.04335568, 27.04327393, 27.02668256, 27.01395882,
       29.89235869, 27.05207807, 27.03972999, 29.90354506, 26.99837416,
       29.91198729, 27.04317928, 27.01251708, 26.99640071, 27.04326926,
       27.04294717, 27.04458277, 27.01940828, 26.99835042, 26.99565124,
       27.04379545, 27.00974335, 27.04290787, 27.04403447, 27.04317729,
       27.05137852, 27.0443867 , 27.03988633, 27.03975176, 27.04340914,
       27.04391525, 27.0438987 , 27.04436385, 27.05254751, 26.99976654,
       27.04476137, 27.04487435, 27.02175396, 27.03889484, 29.90891207,
       27.04310287, 26.99740102, 27.04338636, 27.04374234, 27.04304761,
       27.00116071, 27.04303804, 27.04407393, 27.03384927, 27.03924354,
       27.039571  , 27.04409973, 27.04462705, 26.99877392, 27.00029358,
       29.90674732, 27.04316404, 29.90847165, 27.04390657, 27.03910685,
       27.04443235, 27.00066029, 27.04381339, 27.04333236, 27.04423344,
       27.04316779, 27.03950159, 27.04428317, 29.87796457, 27.03

In [164]:
print('R2_Score :',r2_score(y_test,y_pred))
print('MSE :',mean_squared_error(y_test,y_pred))
print('MAE :',mean_absolute_error(y_test,y_pred))

R2_Score : -0.16848462398392794
MSE : 124.64533892918814
MAE : 9.303709543663448


In [165]:
# Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
# load_iris dataset in sklearn.datasets.
from sklearn.datasets import load_iris
X,y = load_iris(return_X_y=True)

In [166]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=40)

In [167]:
# Feature Scailing
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [168]:
from sklearn.neighbors import KNeighborsClassifier
KNClas = KNeighborsClassifier(n_neighbors=5,weights='distance')
KNClas.fit(X_train_scaled,y_train)

KNeighborsClassifier(weights='distance')

In [169]:
y_pred = KNClas.predict(X_test_scaled)
y_pred

array([0, 1, 2, 2, 1, 2, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 1, 2, 2,
       2, 0, 2, 1, 1, 0])

In [170]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Accuracy_Score :',accuracy_score(y_test,y_pred))
print('Confusion_Matrix :\n',confusion_matrix(y_test,y_pred))
print('\nClassification_Report :\n',classification_report(y_test,y_pred))

Accuracy_Score : 0.96
Confusion_Matrix :
 [[18  0  0]
 [ 0 14  1]
 [ 0  1 16]]

Classification_Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        17

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [201]:
# Q6. Implement a function to standardise the features before applying KNN classifier.
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

def standard_and_KNN(X,y,n_neighbors=6):
    # train test split
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)
    
    # Standard sciling
    scalar = StandardScaler()
    X_train_sclaed = scalar.fit_transform(X_train)
    X_test_sclaed = scalar.transform(X_test)
    
    # Model Training
    Knn = KNeighborsClassifier(n_neighbors=n_neighbors)
    Knn.fit(X_train_sclaed,y_train)
    
    # Model prediction
    y_pred = Knn.predict(X_test_sclaed)
    
    # Model accuracy,classification_report and confusion_matrix
    print('Accuracy Score :',accuracy_score(y_test,y_pred))
    print('\nConfusion Matrix :\n',confusion_matrix(y_test,y_pred))
    print('\nClassification Report :\n',classification_report(y_test,y_pred))
    
    return y_pred,Knn

In [202]:
from sklearn.datasets import load_breast_cancer
X,y = load_breast_cancer(return_X_y=True)

In [208]:
y_pred,knn = standard_and_KNN(X,y,n_neighbors=6)

Accuracy Score : 0.9574468085106383

Confusion Matrix :
 [[ 64   3]
 [  5 116]]

Classification Report :
               precision    recall  f1-score   support

           0       0.93      0.96      0.94        67
           1       0.97      0.96      0.97       121

    accuracy                           0.96       188
   macro avg       0.95      0.96      0.95       188
weighted avg       0.96      0.96      0.96       188



In [209]:
knn

KNeighborsClassifier(n_neighbors=6)

In [210]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1])

In [211]:
# Q7. Write a Python function to calculate the euclidean distance between two points.
import numpy as np
def euclidean(point1,point2):
    point1 = np.array(point1)
    point2 = np.array(point2)
    distance = np.sqrt(np.sum((point1-point2)**2))
    return distance

In [218]:
point1 = [1,2,3]
point2 = [4,5,6]
distance = euclidean(point1,point2)
print(distance)

5.196152422706632


In [222]:
# Q8. Write a Python function to calculate the manhattan distance between two points.
import numpy as np
def mahattan(point1,point2):
    point1 = np.array(point1)
    point2 = np.array(point2)
    man_distance = np.sum(np.abs(point1-point2))
    return man_distance

In [223]:
point1 = [4,5,3]
point2 = [2,6,3]
man_distance = mahattan(point1,point2)
print("Manhattan distance:",man_distance)

Manhattan distance: 3
